### ISSUE TITLE
Enable https:// instead of http:// by default

### ISSUE THREAD

**Issue by yuorme** [yuorme/covid-projections#18]
Right now navigating to www.covid-projections.com takes you to http:// rather than https://

**Comment by patrickvossler18** [comment]
Is the issue here that you've already set up a certificate (self-signed or through Let's Encrypt), but it's still using HTTP, or do you need to set up a certificate?

If you need to get a certificate, I've found [this guide ("Real Certificate" section)](https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https)  pretty helpful.

**Comment by andrewgconnors** [comment]
The certificate is already configured since it works over HTTPS if you specify it, but the server wasn't automatically redirecting all HTTP traffic to HTTPS. I was trying to figure out how to make that happen using Dash hosted on Heroku, but I opened the site and it redirected to HTTPS with code 302, so it looks like you already fixed this, David?

**Comment by yuorme** [comment]
Sorry, was definitely not being clear. Yeah, I've configured SSL certificates on easy mode using Heroku's Automated certificate management.  

The issue whether I can automatically redirect http://www.covid-projections.com to https://www.covid-projections.com. Not sure if this is a DNS setting (I'm using Namecheap) or Heroku setting, or something I can change in the Dash/Flask configuration. Basically enforce HTTPS even if HTTP is specified.

**Comment by yuorme** [comment]
Per @patrickvossler18, we should implement this solution https://github.com/GoogleCloudPlatform/flask-talisman
